accounts/urls.py
from django.conf.urls import url

from rest_framework_jwt.views import obtain_jwt_token

from . import views
from .api.views import (UserList, CreateUser, Profile, PasswordChange, UpdateProfilePicture,
                        VideoUpload, check_credential_availability, check_password)

urlpatterns = [
    url(r'sign-up/$', CreateUser.as_view()),
    url(r'check-credential-availability/', check_credential_availability),
    url(r'sign-in/$', obtain_jwt_token),
    url(r'users/$', UserList.as_view()),
    url(r'users/(?P<public_id>[0-9a-f-]+)/$', Profile.as_view()),
    url(r'change-password/$', PasswordChange.as_view()),
    url(r'check-password/$', check_password),

    url(r'update-profile-picture/$', UpdateProfilePicture.as_view()),
    url(r'new-video/', VideoUpload.as_view(), name='new-video'),
    # password reset
    url(r'begin-password-reset/$', views.begin_password_reset,
        name='begin-password-reset'),
    url(r'password-reset-initiated/$', views.password_reset_initiated,
        name='password-reset-initiated'),
    url(r'password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.reset_password,
        name='password-reset'),
    url(r'password-reset-complete/$', views.reset_password_complete,
        name='password-reset-complete'),
]

core/urls.py
from django.conf.urls import url
from rest_framework_swagger.views import get_swagger_view

from .views import *


schema_view = get_swagger_view(title='Photoshare API')

urlpatterns = [
    url(r'^$', APIHome.as_view(), name="home"),
    url(r'docs/', schema_view),
]

photoshare/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^friends/', include('follows.urls')),
    url(r'^photos/', include('photos.urls')),
    url(r'^notification-feed/', include('feed.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
import uuid
from io import StringIO
from hashlib import md5

import qrcode
from django.conf import settings
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager
from django.contrib.auth.models import Group
from django.core.exceptions import ObjectDoesNotExist
from django.core.files import File
from django.core.files.base import ContentFile
from django.core.mail import send_mail
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import Q
from django.utils import timezone
from django.utils.translation import ugettext_lazy as _

from follows.models import Follow

USER_VIDEO_STATUS = (
    (0, 'Pending'),
    (1, 'Processed')
)

OS_TYPES = (
    (1, 'Android'),
    (2, 'iOS')
)


class CustomUserManager(BaseUserManager):

    def _create_user(self, email, password,
                     is_staff, is_superuser, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email,
                          is_staff=is_staff, is_active=True,
                          is_superuser=is_superuser, last_login=now,
                          date_joined=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        return self._create_user(email, password, False, False,
                                 **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True,
                                 **extra_fields)


class CustomUser(AbstractBaseUser, PermissionsMixin):

    """
    A fully featured User model with admin-compliant permissions that uses
    a full-length email field as the username.

    Email and password are required. Other fields are optional.
    """
    email = models.EmailField(_('email address'), max_length=254, unique=True)
    username = models.CharField(_('username'), max_length=20, unique=True)
    first_name = models.CharField(
        _('first name'), max_length=30, null=True)
    last_name = models.CharField(
        _('last name'), max_length=30, null=True)
    phone_regex = RegexValidator(
        regex=r'^[0-9]{9,15}$', message="Enter a valid phone number (9 - 15 digits).")
    phone_number = models.CharField(
        _('phone number'), max_length=30, null=True, validators=[phone_regex])
    is_staff = models.BooleanField(_('staff status'), default=False,
                                   help_text=_('Designates whether the user can log into this admin '
                                               'site.'))
    is_active = models.BooleanField(_('active'), default=True,
                                    help_text=_('Designates whether this user should be treated as '
                                                'active. Unselect this instead of deleting accounts.'))
    email_verification_key = models.CharField(
        max_length=40, blank=True, null=True)
    email_verification_key_expires = models.DateTimeField(
        blank=True, null=True)
    phone_verification_code = models.IntegerField(blank=True, null=True)
    phone_verification_code_expires = models.DateTimeField(
        blank=True, null=True)
    account_verified_date = models.DateTimeField(blank=True, null=True)
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)
    last_seen = models.DateTimeField(_('last seen'), blank=True, null=True)
    profile_pic = models.ImageField(upload_to='uploads/profile_pics', null=True)
    photoshare_qrcode = models.ImageField(upload_to='photoshare_qrcodes', null=True)
    bio = models.TextField(null=True, blank=True)
    birthday = models.DateField(null=True)

    public_id = models.UUIDField(default=uuid.uuid4, unique=True)

    objects = CustomUserManager()

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = []

    class Meta:
        db_table = "users"
        verbose_name = _('user')
        verbose_name_plural = _('users')
        ordering = ['username']
        default_permissions = ()

    def __str__(self):
        return str(self.get_full_name())

    def get_absolute_url(self):
        return reverse('users', kwargs={'public_id': self.public_id})

    def get_full_name(self):
        """
        Returns the first_name plus the last_name, with a space in between.
        """
        full_name = '%s %s' % (self.first_name, self.last_name)
        return full_name.strip()

    def get_profile_pic(self, size=300):
        """
        Returns user profile pic or default one
        """
        if not self.profile_pic:
            return 'https://www.gravatar.com/avatar/%s?d=identicon&s=%d&?r=pg' % (md5(self.email.encode('utf-8')).hexdigest(), size)
        else:
            return self.profile_pic.url

    def get_short_name(self):
        "Returns the short name for the user."
        return self.first_name

    def email_user(self, subject, message, from_email=None):
        """
        Sends an email to this User.
        """
        send_mail(subject, message, from_email, [self.email])


class ProfileVideo(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    video_file = models.FileField(upload_to='user_videos')
    date_uploaded = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=USER_VIDEO_STATUS, default=0)
    os_type = models.PositiveIntegerField(choices=OS_TYPES, null=True)

    class Meta:
        db_table = 'user_videos'
        default_permissions = ()

accounts/forms.py
from django import forms
from django.contrib.auth.forms import PasswordResetForm, SetPasswordForm


class BeginPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'class': 'form-control',
        'autocomplete': 'off'
    }))


class MySetpasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))
    new_password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'class': 'form-control'
    }))

accounts/api/views.py
import json
from io import FileIO, BufferedWriter

from django.contrib.auth import get_user_model
from django.core.exceptions import ObjectDoesNotExist
from django.core.files.temp import NamedTemporaryFile
from django.db.models import Q
from rest_framework import status
from rest_framework.decorators import api_view, permission_classes
from rest_framework.generics import CreateAPIView, GenericAPIView, ListAPIView, UpdateAPIView
from rest_framework.mixins import (UpdateModelMixin, RetrieveModelMixin)
from rest_framework.parsers import MultiPartParser, FormParser
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView
from rest_framework_jwt.settings import api_settings

from accounts.models import ProfileVideo
from photoshare.settings import r
from .serializers import (UserSerializer, PasswordChangeSerializer, ProfilePictureSerializer,
                          VideoUploadSerializer, GeneralUserSerializer)

User = get_user_model()


class CreateUser(CreateAPIView):
    permission_classes = (AllowAny, )
    serializer_class = UserSerializer
    queryset = User.objects.all()

    def post(self, request, *args, **kwargs):
        """
        Registers a new user
        """
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            user = serializer.save()

            # login user
            jwt_payload_handler = api_settings.JWT_PAYLOAD_HANDLER
            jwt_encode_handler = api_settings.JWT_ENCODE_HANDLER
            jwt_response_handler = api_settings.JWT_RESPONSE_PAYLOAD_HANDLER

            payload = jwt_payload_handler(user)
            token = jwt_encode_handler(payload)

            response = jwt_response_handler(token, user)

            return Response(response, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
@permission_classes((AllowAny, ))
def check_credential_availability(request):
    if 'email' in request.query_params and request.query_params.get('email') is not None:
        try:
            User.objects.get(email=request.query_params['email'])
            return Response({'available': False})
        except ObjectDoesNotExist:
            return Response({'available': True})
    if 'username' in request.query_params and request.query_params.get('username') is not None:
        try:
            User.objects.get(username=request.query_params['username'])
            return Response({'available': False})
        except ObjectDoesNotExist:
            return Response({'available': True})
    return Response(status=status.HTTP_404_NOT_FOUND)


@api_view(['POST'])
def check_password(request):
    password = request.data['password']
    user = request.user
    if user.check_password(password):
        return Response({'valid': True})
    else:
        return Response({'valid': False})


class UserList(ListAPIView):
    serializer_class = GeneralUserSerializer

    def get(self, request, *args, **kwargs):
        return self.list(request, *args, **kwargs)

    def get_queryset(self):
        q = self.request.query_params.get('q', None)
        users = []
        if q is not None:
            users = User.objects.filter(
                Q(first_name__icontains=q) | Q(last_name__icontains=q) | Q(username__icontains=q)
            ).exclude(pk=self.request.user.pk)
        else:
            users = User.objects.all()
        return users

    def paginate_queryset(self, queryset):
        return None


class Profile(RetrieveModelMixin, UpdateModelMixin, GenericAPIView):
    queryset = User.objects.all()
    lookup_field = 'public_id'
    lookup_url_kwarg = 'public_id'

    def get(self, request, *args, **kwargs):
        """
        Returns a user's profile
        """
        return self.retrieve(request, *args, **kwargs)

    def get_serializer_class(self):
        user = self.get_object()
        request_user = self.request.user

        if user == request_user:
            return UserSerializer
        else:
            return GeneralUserSerializer

    def patch(self, request, public_id):
        """
        Updates a user's profile - name, birthday, bio
        """
        user = self.get_object()
        if user is not None and user == request.user:
            serializer = UserSerializer(user, data=request.data, partial=True)
            if serializer.is_valid():
                serializer.save()
                return Response(serializer.data, status=status.HTTP_200_OK)
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)
        return Response(status=status.HTTP_400_BAD_REQUEST)


class PasswordChange(UpdateAPIView):
    serializer_class = PasswordChangeSerializer
    model = User

    def get_object(self):
        obj = self.request.user
        return obj

    def update(self, request, *args, **kwargs):
        obj = self.get_object()
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            current_password = serializer.data['current_password']
            new_password = serializer.data['new_password']

            # check if current password is valid
            if not obj.check_password(current_password):
                return Response({'msg': 'Invalid current password'}, status=status.HTTP_401_UNAUTHORIZED)

            obj.set_password(new_password)
            obj.save(update_fields=['password'])
            return Response({'msg': 'Password updated successfully'}, status=status.HTTP_200_OK)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class UpdateProfilePicture(UpdateAPIView):
    parser_classes = (MultiPartParser, FormParser, )
    serializer_class = ProfilePictureSerializer

    def get_object(self):
        return self.request.user

    def update(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            user = self.get_object()
            profile_pic = request.data['profile_pic']
            user.profile_pic.save(profile_pic.name, profile_pic)
            return Response({'profile_pic': request.build_absolute_uri(user.profile_pic.url)}, status=status.HTTP_200_OK)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)


class VideoUpload(APIView):
    serializer_class = VideoUploadSerializer
    parser_classes = (MultiPartParser, FormParser, )

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            profile_video = serializer.save(user=request.user)

            pub_msg = {
                "task_type": 1,
                "user_id": request.user.pk,
                "video_path": '/opt/photoshare_v2/photoshare' + profile_video.video_file.url,
                "os_type": profile_video.os_type
            }

            r.publish('recognition_tasks', json.dumps(pub_msg))

            return Response({}, status=201)
        else:
            return Response(status=status.HTTP_400_BAD_REQUEST)


@api_view(['GET'])
def get_qr_code(request):
    return Response({'qr_code': request.user.tink_qrcode.url})

accounts/views.py
from django.contrib.auth.views import password_reset, password_reset_confirm
from django.core.urlresolvers import reverse
from django.shortcuts import render

from accounts.forms import BeginPasswordResetForm, MySetpasswordForm


def begin_password_reset(request):
    return password_reset(request, template_name='password_reset_begin.html',
                          password_reset_form=BeginPasswordResetForm,
                          email_template_name='notifications/begin_password_reset.html',
                          html_email_template_name='notifications/begin_password_reset.html',
                          subject_template_name='notifications/begin_password_reset_subject.txt',
                          post_reset_redirect=reverse('password-reset-initiated'))


def password_reset_initiated(request):
    return render(request, 'password_reset_initiated.html')


def reset_password(request, uidb64=None, token=None):
    return password_reset_confirm(request,
                                  template_name='password_reset_confirm.html',
                                  set_password_form=MySetpasswordForm,
                                  uidb64=uidb64, token=token,
                                  post_reset_redirect=reverse('password-reset-complete'))


def reset_password_complete(request):
    return render(request, 'password_reset_complete.html')

accounts/templates/auth_base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>{% block title %} {% endblock %} &middot; Photoshare</title>

	<!-- Global stylesheets -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <style type="text/css">

        body {
          background: #eee !important;
        }

        .wrapper {
          margin-top: 80px;
          margin-bottom: 80px;
        }

        .form-signin {
          max-width: 380px;
          padding: 15px 35px 45px;
          margin: 0 auto;
          background-color: #fff;
          border: 1px solid rgba(0, 0, 0, 0.1);
        }
        .form-signin .form-signin-heading,
        .form-signin button {
          margin-bottom: 30px;
        }
        .form-signin {
          font-weight: normal;
        }
        .form-signin .form-control {
          position: relative;
          font-size: 16px;
          height: auto;
          padding: 10px;
          -webkit-box-sizing: border-box;
          -moz-box-sizing: border-box;
          box-sizing: border-box;
        }
        .form-signin .form-control:focus {
          z-index: 2;
        }
        .form-signin input[type="email"] {
          margin-bottom: 30px;
          border-bottom-left-radius: 0;
          border-bottom-right-radius: 0;
        }
    </style>
	<!-- /global stylesheets -->

</head>
<body>

	  <div class="wrapper">
          {% block content %} {% endblock %}
      </div>

</body>
</html>

accounts/templates/password_reset_begin.html
{% extends "auth_base.html" %}

{% block title %} Password Reset {% endblock %}

{% block content %}

    <form class="form-signin" method="post" action=".">
        {% csrf_token %}
          <h3 class="form-signin-heading">Enter your email</h3>
          {{ form.email }}
          <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
    </form>

{% endblock %}

accounts/templates/password_reset_complete.html
{% extends "auth_base.html" %}
{% block title %} Password Reset {% endblock %}
{% block content %}

    <p>
        Password reset has been completed successfully. You can now sign in to your Photoshare account from the Photoshare app!
    </p>

{% endblock %}

accounts/templates/password_reset_confirm.html
{% extends "auth_base.html" %}

{% block title %} Password Reset {% endblock %}

{% block content %}<!-- deckHolder -->

    {% if message %}
        {{ message }}
    {% endif %}

    {% if validlink %} <!-- If the link is valid, display a confirmation page, else display an error message -->
        <form action="." method="post" class="form-signin">
            {% csrf_token %} <!-- CSRF token is rendered by Django in forms to avoid CSRF attacks -->
            <!-- If there are non-field errors in the form,
                iterate over them one by one and display them.
            -->
            <div class="panel panel-body login-form">
                <div class="text-center">
                    <div class="icon-object border-warning text-warning"><i class="icon-lock5"></i></div>
                    <h5 class="content-group">Enter your new password</h5>
                </div>
                <div class="form-group">
                    <label for="id_new_password1" class="control-label">New Password</label>
                    {{ form.new_password1 }}
                    <span class="form-errors">{{ form.new_password1.errors }}</span>
                </div>
                <div class="form-group">
                    <label for="id_new_password2" class="control-label">Confirm Password</label>
                    {{ form.new_password2 }}
                    <span class="form-errors">{{ form.new_password2.errors }}</span>
                </div>
                <button class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
            </div>
        </form>
    {% else %} <!-- Since the confirmation link is invalid, display an error message -->
        <div class="error-msg">
            Invalid password reset link
        </div>
    {% endif %}

{% endblock %}

accounts/templates/password_reset_initiated.html
{% extends "auth_base.html" %}
{% block title %} Password Reset {% endblock %}
{% block content %}

    <h3>Check your email</h3>

    <p>
        We've sent an email to the email address you provided. Click the link in the email to reset your password.
        <br>
        If you don't see the email, check other places it might be, like your junk, spam, social or other folders.
    </p>

{% endblock %}

accounts/templates/verify_email.html
<!DOCTYPE html>
<html>
<head>
	<title>Email Verification</title>
</head>
<body>
	<h1>
		Email verification successful.
	</h1>
</body>
</html>